services:
  flask-app:
    build: . # Uncomment this if you need to build 
    image: ghcr.io/jodegreef/dune-weaver:main # Use latest production image
    restart: always
    ports:
      - "8080:8080" # Map port 8080 of the container to 8080 of the host
    volumes:
      - .:/app
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    privileged: true
    environment:
      - FLASK_ENV=development # Set environment variables for Flask
      - TZ=Europe/Brussels
    container_name: flask-theta-rho-app
